### PR TITLE
Added mushroom people sentence

### PR DESCRIPTION
**Pull request by ajgarner98**
Added sentence, please review.

### CODE REVIEW

**Review by melo616 — APPROVED** [review]
Amazing sentence

**Review by brendareyes-techprep — APPROVED** [review]
Good job, Andre!

**Review by chiucarman — APPROVED** [review]
i approve this message

**Review by EthanKH — APPROVED** [review]
Thank you pizza man for including mushrooms

**Review by thatcantbeso — APPROVED** [review]
great !

**Pull request merged**
