### PR TITLE
Added my sentence to story

### PR DESCRIPTION
**Pull request by thatcantbeso**

### CODE REVIEW

**Review by brendareyes-techprep — APPROVED** [review]
Thanks for that.

**Review by melo616 — APPROVED** [review]

**Review by alejlopez139 — APPROVED** [review]
a giant penguin? fascinating

**Review by brendareyes-techprep — APPROVED** [review]
ok

**Review by EthanKH — APPROVED** [review]
i hope the penguin is cute (◕‿◕✿)

**Review by brendareyes-techprep — APPROVED** [review]

**Review by ajgarner98 — APPROVED** [review]
Pengu!

**Pull request merged**
