### PR TITLE
Added a sentence to in a world

### PR DESCRIPTION
**Pull request by ajmompr**
added a sentence to "in a world" story

### CODE REVIEW

**Review by JaredBears — APPROVED** [review]

**Review by Brian-Waddell — APPROVED** [review]
Great job Alex

**Review by CarlosCastanedaDev — APPROVED** [review]
Great!

**Review by alejlopez139 — APPROVED** [review]
Vortex adventure!

**Review by brendareyes-techprep — APPROVED** [review]

**Review by fidel-techprep — APPROVED** [review]
This is getting wordy hahaha

**Review by flstudio4 — APPROVED** [review]
Good!

**Pull request merged**
